name: Build waterctl image

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build waterctl image
    runs-on: ubuntu-latest
    if: (github.event.workflow_run.conclusion == 'success' && github.repository == 'zhangjiain/waterctl') || (github.repository == 'zhangjiain/waterctl')

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
          
      - name: Set Docker image tag based on repository
        id: set-tag
        run: |
          if [ "${{ github.repository }}" = "zhangjiain/waterctl" ]; then
            echo "IMAGE_TAG=waterctl:latest" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=waterctl-beta:latest" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push waterctl image
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/${{ steps.set-tag.outputs.IMAGE_TAG }}"
          platforms: linux/amd64,linux/arm64/v8
